default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["PG_DB_HOST"] %>
  port: <%= ENV["PG_DB_PORT"] %>
  username: <%= ENV["PG_DB_USER_NAME"] %>
  password: <%= ENV["PG_DB_PASSWORD"] %>

development:
  <<: *default
  database: wallet_development

test:
  <<: *default
  database: wallet_test

production:
  <<: *default
  database: wallet_production
  username: wallet
  password: <%= ENV['WALLET_DATABASE_PASSWORD'] %>
